import { supabase, obtenerSesion, cerrarSesion } from './supabase-config.js';

let colaboradores=[];
let esAdmin=false;
const actividades=['Limpieza - Andén','Limpieza - Parqueo','Limpieza - Bodega','Limpieza - Área Externa','Limpieza - Bodega 095','Limpieza - Bodega 033','Ordenamiento de Bodega','Rotulación de Ingresos'];
const tipos=['Café','Representada','Mixto'];
const timers=new Map();

const slug=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\W+/g,'-').toLowerCase();
const fmt=s=>{s=Math.max(0,Number(s||0));return [Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(v=>String(v).padStart(2,'0')).join(':')};
const hoy=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const keyTimer=(cat,id)=>`${cat}|${id}`;

function segundosActuales(t){
  const base=Number(t?.segundos_acumulados||0);
  return t?.estado==='ejecucion'&&t.inicio?base+Math.max(0,Math.floor((Date.now()-new Date(t.inicio).getTime())/1000)):base;
}
function tarjetaPrep(c){const id=c.id;return `<article class="worker" id="card-prep-${id}"><h3>${esc(c.nombre)}</h3><div class="form"><div><label>Fecha</label><input id="prep-fecha-${id}" type="date" value="${hoy()}"></div><div><label>Zona</label><input id="prep-zona-${id}" placeholder="Zona o gira"></div><div><label>Tipo</label><select id="prep-tipo-${id}"><option value="">Seleccione</option>${tipos.map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>Facturas</label><input id="prep-facturas-${id}" type="number" min="1"></div><div><label>Libras de la gira</label><input id="prep-libras-${id}" type="number" min="0" step=".01"></div></div><div class="timer" id="timer-prep-${id}">00:00:00</div><div class="desc" id="desc-prep-${id}">Sin preparación activa</div><div class="conflict" id="conflict-prep-${id}"></div><div class="actions">${botones('preparacion',c)}</div></article>`}
function tarjetaAct(c){const id=c.id;return `<article class="worker" id="card-act-${id}"><h3>${esc(c.nombre)}</h3><div class="form"><div><label>Fecha</label><input id="act-fecha-${id}" type="date" value="${hoy()}"></div><div style="grid-column:span 2"><label>Actividad</label><select id="act-tipo-${id}"><option value="">Seleccione</option>${actividades.map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="timer" id="timer-act-${id}">00:00:00</div><div class="desc" id="desc-act-${id}">Sin actividad activa</div><div class="conflict" id="conflict-act-${id}"></div><div class="actions">${botones('actividad',c)}</div></article>`}
function botones(cat,c){return `<button class="primary" data-requires-online data-action="start" data-cat="${cat}" data-collab="${c.id}">Iniciar</button><button class="warn" data-requires-online data-action="pause" data-cat="${cat}" data-collab="${c.id}">Pausar</button><button class="primary" data-requires-online data-action="resume" data-cat="${cat}" data-collab="${c.id}">Continuar</button><button class="ok" data-requires-online data-action="finish" data-cat="${cat}" data-collab="${c.id}">Finalizar</button><button class="danger" data-requires-online data-action="cancel" data-cat="${cat}" data-collab="${c.id}">Cancelar</button>`}
function renderColaboradores(){document.getElementById('prepWorkers').innerHTML=colaboradores.map(tarjetaPrep).join('');document.getElementById('actWorkers').innerHTML=colaboradores.map(tarjetaAct).join('')}
function detalleTimer(t){const d=t.datos||{};return t.categoria==='preparacion'?`${d.zona||'Sin zona'} · ${d.tipo||'Sin tipo'} · ${d.facturas||0} facturas · ${Number(d.libras||0).toFixed(2)} lb`:d.actividad||'Actividad sin detalle'}
function renderActivosSuperiores(){const dock=document.getElementById('activeDock'),list=document.getElementById('activeList'),count=document.getElementById('activeCount');const activos=[...timers.values()].sort((a,b)=>String(a.empleado).localeCompare(String(b.empleado)));count.textContent=activos.length;dock.classList.toggle('visible',activos.length>0);list.innerHTML=activos.map(t=>{const paused=t.estado==='pausado';const pref=t.categoria==='preparacion'?'prep':'act';return `<article class="active-item ${paused?'paused':''}"><div class="active-item-main"><div class="active-item-top"><span class="active-kind">${t.categoria==='preparacion'?'Preparación':'Actividad'}</span><span class="active-person">${esc(t.empleado)}</span></div><div class="active-detail">${esc(detalleTimer(t))}</div></div><div><div class="active-clock" data-dock-clock="${t.id}">${fmt(segundosActuales(t))}</div><div class="active-state">${paused?'PAUSADO':'EN EJECUCIÓN'}</div></div><div class="active-quick"><button class="focus-btn" data-focus-card="${pref}|${t.colaborador_id}">Ver detalle</button>${paused?`<button class="primary" data-action="resume" data-cat="${t.categoria}" data-collab="${t.colaborador_id}">Continuar</button>`:`<button class="warn" data-action="pause" data-cat="${t.categoria}" data-collab="${t.colaborador_id}">Pausar</button>`}<button class="ok" data-action="finish" data-cat="${t.categoria}" data-collab="${t.colaborador_id}">Finalizar</button></div></article>`}).join('')}

document.getElementById('dockToggle')?.addEventListener('click',()=>{const d=document.getElementById('activeDock');d.classList.toggle('collapsed');document.getElementById('dockToggle').textContent=d.classList.contains('collapsed')?'Mostrar':'Ocultar'});
document.addEventListener('click',e=>{const b=e.target.closest('[data-focus-card]');if(!b)return;const [pref,id]=b.dataset.focusCard.split('|');document.getElementById(`card-${pref}-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'})});
function datosFormulario(cat,id){if(cat==='preparacion'){const d={fecha_preparacion:document.getElementById(`prep-fecha-${id}`).value,zona:document.getElementById(`prep-zona-${id}`).value.trim(),tipo:document.getElementById(`prep-tipo-${id}`).value,facturas:Number(document.getElementById(`prep-facturas-${id}`).value||0),libras:Number(document.getElementById(`prep-libras-${id}`).value||0)};if(!d.fecha_preparacion||!d.zona||!d.tipo||d.facturas<=0||d.libras<0)throw new Error('Complete fecha, zona, tipo, facturas y libras.');return d}const d={fecha:document.getElementById(`act-fecha-${id}`).value,actividad:document.getElementById(`act-tipo-${id}`).value};if(!d.fecha||!d.actividad)throw new Error('Seleccione fecha y actividad.');return d}
function mostrarConflicto(cat,id,msg){const el=document.getElementById(`conflict-${cat==='preparacion'?'prep':'act'}-${id}`);if(!el)return;el.textContent=msg;el.style.display='block';setTimeout(()=>el.style.display='none',6000)}
async function rpc(nombre,args){const {data,error}=await supabase.rpc(nombre,args);if(error)throw error;return data}
async function iniciar(cat,id){if(!navigator.onLine)return mostrarConflicto(cat,id,'Sin conexión. La operación debe validarse en Supabase.');try{await rpc('iniciar_cronometro_v2',{p_categoria:cat,p_colaborador_id:id,p_datos:datosFormulario(cat,id)});await cargarTodo()}catch(e){mostrarConflicto(cat,id,e.message.includes('CRONOMETRO_ACTIVO_EXISTENTE')?'Ya existe un cronómetro activo para este colaborador.':e.message)}}
async function accionar(cat,id,accion){if(!navigator.onLine)return mostrarConflicto(cat,id,'Sin conexión.');const t=timers.get(keyTimer(cat,id));if(!t)return mostrarConflicto(cat,id,'No existe un cronómetro activo.');try{if(accion==='finish')await rpc('finalizar_cronometro',{p_id:t.id,p_expected_version:t.version});else if(accion==='cancel')await rpc('cancelar_cronometro',{p_id:t.id,p_expected_version:t.version});else await rpc('cambiar_estado_cronometro',{p_id:t.id,p_expected_version:t.version,p_accion:accion});await cargarTodo()}catch(e){mostrarConflicto(cat,id,'Fue modificado desde otro dispositivo. Se cargará la versión vigente.');await cargarTodo()}}
document.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const {action,cat,collab}=b.dataset;action==='start'?iniciar(cat,collab):accionar(cat,collab,action)});
function aplicarTimer(t){timers.set(keyTimer(t.categoria,t.colaborador_id),t);const id=t.colaborador_id,pref=t.categoria==='preparacion'?'prep':'act',card=document.getElementById(`card-${pref}-${id}`);if(!card)return;card.classList.add('active');document.getElementById(`timer-${pref}-${id}`).textContent=fmt(segundosActuales(t));const d=t.datos||{};document.getElementById(`desc-${pref}-${id}`).textContent=t.estado==='pausado'?'Pausado':detalleTimer(t);if(t.categoria==='preparacion'){document.getElementById(`prep-fecha-${id}`).value=d.fecha_preparacion||hoy();document.getElementById(`prep-zona-${id}`).value=d.zona||'';document.getElementById(`prep-tipo-${id}`).value=d.tipo||'';document.getElementById(`prep-facturas-${id}`).value=d.facturas||'';document.getElementById(`prep-libras-${id}`).value=d.libras||''}else{document.getElementById(`act-fecha-${id}`).value=d.fecha||hoy();document.getElementById(`act-tipo-${id}`).value=d.actividad||''}}
function limpiarTarjetas(){timers.clear();renderColaboradores()}
async function cargarTodo(){const [{data:cols,error:ec},{data:activos,error:e1},{data:prep,error:e2},{data:acts,error:e3}]=await Promise.all([supabase.from('colaboradores').select('*').eq('activo',true).order('orden').order('nombre'),supabase.from('cronometros').select('*').in('estado',['ejecucion','pausado']),supabase.from('historial_preparaciones').select('*').order('created_at',{ascending:false}).limit(200),supabase.from('historial_actividades').select('*').order('created_at',{ascending:false}).limit(200)]);if(ec||e1||e2||e3)throw ec||e1||e2||e3;colaboradores=cols||[];limpiarTarjetas();(activos||[]).forEach(aplicarTimer);renderActivosSuperiores();document.getElementById('prepHistory').innerHTML=(prep||[]).map(r=>`<tr><td>${new Date(r.created_at).toLocaleString('es-HN')}</td><td>${esc(r.empleado)}</td><td>${esc(r.zona)}</td><td>${esc(r.tipo)}</td><td>${r.facturas}</td><td>${Number(r.libras).toFixed(2)}</td><td>${fmt(r.segundos)}</td><td>${esc(r.finalizado_por_email||'')}</td></tr>`).join('');document.getElementById('actHistory').innerHTML=(acts||[]).map(r=>`<tr><td>${new Date(r.created_at).toLocaleString('es-HN')}</td><td>${esc(r.empleado)}</td><td>${esc(r.actividad)}</td><td>${fmt(r.segundos)}</td><td>${esc(r.finalizado_por_email||'')}</td></tr>`).join('');document.getElementById('conexion').textContent='Conectado. Datos sincronizados con Supabase.'}

async function verificarAdmin(userId){const {data}=await supabase.from('perfiles').select('rol').eq('id',userId).maybeSingle();esAdmin=data?.rol==='admin';document.getElementById('adminOpenBtn').hidden=!esAdmin}
async function cargarAdmin(){if(!esAdmin)return;const {data,error}=await supabase.from('colaboradores').select('*').order('activo',{ascending:false}).order('orden').order('nombre');if(error)throw error;document.getElementById('collabTable').innerHTML=(data||[]).map(c=>`<tr><td>${esc(c.nombre)}</td><td>${esc(c.codigo||'')}</td><td><span class="${c.activo?'status-active':'status-inactive'}">${c.activo?'Activo':'Inactivo'}</span></td><td><button class="light" data-edit-collab='${JSON.stringify({id:c.id,nombre:c.nombre,codigo:c.codigo||''}).replace(/'/g,"&#39;")}'>Editar</button> <button class="${c.activo?'danger':'ok'}" data-toggle-collab="${c.id}" data-new-state="${!c.activo}">${c.activo?'Desactivar':'Activar'}</button></td></tr>`).join('')}
const panel=document.getElementById('adminPanel');document.getElementById('adminOpenBtn').addEventListener('click',async()=>{panel.hidden=false;await cargarAdmin();panel.scrollIntoView({behavior:'smooth'})});document.getElementById('adminCloseBtn').addEventListener('click',()=>panel.hidden=true);document.getElementById('collabCancelEdit').addEventListener('click',()=>document.getElementById('collabForm').reset());
document.getElementById('collabForm').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('collabId').value||null,nombre=document.getElementById('collabNombre').value.trim(),codigo=document.getElementById('collabCodigo').value.trim()||null;try{await rpc('admin_guardar_colaborador',{p_id:id,p_nombre:nombre,p_codigo:codigo});e.target.reset();document.getElementById('collabId').value='';await Promise.all([cargarAdmin(),cargarTodo()]);document.getElementById('adminMessage').textContent='Colaborador guardado correctamente.'}catch(err){document.getElementById('adminMessage').textContent=err.message}});
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-collab]');if(edit){const c=JSON.parse(edit.dataset.editCollab);document.getElementById('collabId').value=c.id;document.getElementById('collabNombre').value=c.nombre;document.getElementById('collabCodigo').value=c.codigo;return}const tog=e.target.closest('[data-toggle-collab]');if(tog){try{await rpc('admin_cambiar_estado_colaborador',{p_id:tog.dataset.toggleCollab,p_activo:tog.dataset.newState==='true'});await Promise.all([cargarAdmin(),cargarTodo()])}catch(err){document.getElementById('adminMessage').textContent=err.message}}});

setInterval(()=>{timers.forEach(t=>{const pref=t.categoria==='preparacion'?'prep':'act',el=document.getElementById(`timer-${pref}-${t.colaborador_id}`);if(el)el.textContent=fmt(segundosActuales(t));const d=document.querySelector(`[data-dock-clock="${t.id}"]`);if(d)d.textContent=fmt(segundosActuales(t))})},1000);
const ses=await obtenerSesion();if(!ses.ok||!ses.session)location.replace('./index.html');else{document.getElementById('userEmail').textContent=ses.session.user.email||'Usuario';await verificarAdmin(ses.session.user.id)}
window.salir=async()=>{await cerrarSesion();location.replace('./index.html')};
supabase.channel('cronometros-operacion-v12').on('postgres_changes',{event:'*',schema:'public',table:'cronometros'},()=>cargarTodo()).on('postgres_changes',{event:'*',schema:'public',table:'historial_preparaciones'},()=>cargarTodo()).on('postgres_changes',{event:'*',schema:'public',table:'historial_actividades'},()=>cargarTodo()).on('postgres_changes',{event:'*',schema:'public',table:'colaboradores'},()=>{cargarTodo();if(esAdmin)cargarAdmin()}).subscribe();
try{await cargarTodo()}catch(e){document.getElementById('conexion').textContent='No se pudo cargar la información: '+e.message}
